spring.application.name=api-gateway
server.port=8080

# Service registry
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

# SERVICE URL
ecom.product.service.url=lb://product-service
ecom.user.service.url=lb://product-service

# PRODUCT SERVICE
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${ecom.product.service.url}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/products/**

spring.cloud.gateway.server.webmvc.routes[1].id=category-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${ecom.product.service.url}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/categories/**

spring.cloud.gateway.server.webmvc.routes[2].id=product-search
spring.cloud.gateway.server.webmvc.routes[2].uri=${ecom.product.service.url}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/products/search/**

# USER SERVICE
spring.cloud.gateway.server.webmvc.routes[3].id=user-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${ecom.user.service.url}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/users/**