spring.application.name=api-gateway
server.port=8080


product-service.url=http://localhost:8081

spring.cloud.gateway.server.webmvc.routes[0].id=categories
spring.cloud.gateway.server.webmvc.routes[0].uri=${product-service.url}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=path=/api/v1/categories/**

spring.cloud.gateway.server.webmvc.routes[1].id=products
spring.cloud.gateway.server.webmvc.routes[1].uri=${product-service.url}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=/api/v1/products/**


user-service.url=http://localhost:8082

spring.cloud.gateway.server.webmvc.routes[2].id=user
spring.cloud.gateway.server.webmvc.routes[2].uri=${user-service.url}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=path=/api/v1/users/**
